#!/bin/sh

IN="pl_PL"
OUT="polish"
ENCODING="ISO8859-2"

echo "Generating files for \"$IN\" language"

wget "https://raw.githubusercontent.com/LibreOffice/dictionaries/master/pl_PL/pl_PL.aff"
wget "https://raw.githubusercontent.com/LibreOffice/dictionaries/master/pl_PL/pl_PL.dic"

# Remove first line (from docs)
# > The first  line of the dictionaries (except personal dictionaries) contains
# > the approximate word count (for optimal hash memory  size).
sed -i '1d' "$IN.dic"

# Encode as UTF-8
iconv -f "$ENCODING" -t utf8 -o "$IN.utf.dic" "$IN.dic"
iconv -f "$ENCODING" -t utf8 -o "$OUT.affix"  "$IN.aff"

# Switch back .utf for dic
rm "$IN.dic"
mv "$IN.utf.dic" "$IN.dic"

# Concat the dic and dic_delta, sort alphabetically and remove the leading
# blank line (leaves the ending newline intact)
export LC_ALL="$IN.UTF-8"

# Removes the blank line at the top and sorts files
sort "$IN.dic" | sed '/^$/d' > "$OUT.dict"

# Remove temp files
rm "$IN.dic" "$IN.aff"

# Offer to install in Debian/Ubuntu
if command -v pg_config > /dev/null 2>&1; then
	PG_TSEARCH_DATA="$(pg_config --sharedir)/tsearch_data";
	PG_VERSION=$(pg_config --version);
	echo "Attempting install for $PG_VERSION to $PG_TSEARCH_DATA";
	sudo cp "$OUT.stop" "$OUT.affix" "$OUT.dict" "$PG_TSEARCH_DATA"
fi;

echo "Finished!"
